//-*-C++-*-

/*! 
 * 	 \class function_operator_collection 
 * 	 \brief This is a C++ file generated by write_function_operations.py. It lists all the function-operator(...) methods 
 * 	 \author Peter Staar  
 */ 


template<typename scalartype>
struct function_operators_collection{
 public: 

scalartype& operator()( int i0,  int i1);
scalartype& operator()( int i0,  int i1,  int i2);
scalartype& operator()( int i0,  int i1,  int i2,  int i3);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17);
scalartype& operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17,  int i18);

};
