//-*-C++-*-

/*! 
 * 	 \class function 
  * 	 rief This is a C++ file generated by write_function_operations.py. It implements the operator(...) methods 
 * 	 author: Peter Staar  
 */ 


inline scalartype&  operator()( int i0,  int i1)
{
return fnc_values[ dmn( i0,  i1)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2)
{
return fnc_values[ dmn( i0,  i1,  i2)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15,  i16)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15,  i16,  i17)];
}

inline scalartype&  operator()( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17,  int i18)
{
return fnc_values[ dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15,  i16,  i17,  i18)];
}

