//-*-C++-*-

/*! 
 * 	 \class  subind_2_linind_collection.h 
  * 	 \brief  This is a C++ file generated by write_function_operations.py. It implements the conversion from coordinates to linear index. 
 * 	 \author Peter Staar  
 */ 


template<typename scalartype>
struct subind_2_linind_collection{
 public: 

int subind_2_linind( int i0,  int i1);
int subind_2_linind( int i0,  int i1,  int i2);
int subind_2_linind( int i0,  int i1,  int i2,  int i3);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17);
int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17,  int i18);

};
