//-*-C++-*-

/*! 
 * 	 \class  subind_2_linind 
  * 	 \brief  This is a C++ file generated by write_function_operations.py. It implements the operator(...) methods 
 * 	 \author Peter Staar  
 */ 


int subind_2_linind( int i0,  int i1)
{
return dmn( i0,  i1);
}

int subind_2_linind( int i0,  int i1,  int i2)
{
return dmn( i0,  i1,  i2);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3)
{
return dmn( i0,  i1,  i2,  i3);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4)
{
return dmn( i0,  i1,  i2,  i3,  i4);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15,  i16);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15,  i16,  i17);
}

int subind_2_linind( int i0,  int i1,  int i2,  int i3,  int i4,  int i5,  int i6,  int i7,  int i8,  int i9,  int i10,  int i11,  int i12,  int i13,  int i14,  int i15,  int i16,  int i17,  int i18)
{
return dmn( i0,  i1,  i2,  i3,  i4,  i5,  i6,  i7,  i8,  i9,  i10,  i11,  i12,  i13,  i14,  i15,  i16,  i17,  i18);
}

