//-*-C++-*-

/* 
 * 	 This is a C++ file generated by write_domain_type_operation.py 
 *
 * 	 author: Peter Staar  
 */ 

#include "type_list_definitions.h" 


#ifndef DOMAIN_TYPE_OPERATIONS_H_
#define DOMAIN_TYPE_OPERATIONS_H_

namespace TL 
{



/****************************************
***           ERASE                   ***
*****************************************/



template<class T0, class T1> 
struct Erase {}; 

template <class T0 , class T1 >
struct Erase<dmn_2< T0, T1>, T0> {
typedef dmn_1<T1> Result;
}; 

template <class T0 , class T1 >
struct Erase<dmn_2< T0, T1>, T1> {
typedef dmn_1<T0> Result;
}; 

template <class T0 , class T1 , class T2 >
struct Erase<dmn_3< T0, T1, T2>, T0> {
typedef dmn_2<T1, T2> Result;
}; 

template <class T0 , class T1 , class T2 >
struct Erase<dmn_3< T0, T1, T2>, T1> {
typedef dmn_2<T0, T2> Result;
}; 

template <class T0 , class T1 , class T2 >
struct Erase<dmn_3< T0, T1, T2>, T2> {
typedef dmn_2<T0, T1> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 >
struct Erase<dmn_4< T0, T1, T2, T3>, T0> {
typedef dmn_3<T1, T2, T3> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 >
struct Erase<dmn_4< T0, T1, T2, T3>, T1> {
typedef dmn_3<T0, T2, T3> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 >
struct Erase<dmn_4< T0, T1, T2, T3>, T2> {
typedef dmn_3<T0, T1, T3> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 >
struct Erase<dmn_4< T0, T1, T2, T3>, T3> {
typedef dmn_3<T0, T1, T2> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 >
struct Erase<dmn_5< T0, T1, T2, T3, T4>, T0> {
typedef dmn_4<T1, T2, T3, T4> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 >
struct Erase<dmn_5< T0, T1, T2, T3, T4>, T1> {
typedef dmn_4<T0, T2, T3, T4> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 >
struct Erase<dmn_5< T0, T1, T2, T3, T4>, T2> {
typedef dmn_4<T0, T1, T3, T4> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 >
struct Erase<dmn_5< T0, T1, T2, T3, T4>, T3> {
typedef dmn_4<T0, T1, T2, T4> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 >
struct Erase<dmn_5< T0, T1, T2, T3, T4>, T4> {
typedef dmn_4<T0, T1, T2, T3> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
struct Erase<dmn_6< T0, T1, T2, T3, T4, T5>, T0> {
typedef dmn_5<T1, T2, T3, T4, T5> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
struct Erase<dmn_6< T0, T1, T2, T3, T4, T5>, T1> {
typedef dmn_5<T0, T2, T3, T4, T5> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
struct Erase<dmn_6< T0, T1, T2, T3, T4, T5>, T2> {
typedef dmn_5<T0, T1, T3, T4, T5> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
struct Erase<dmn_6< T0, T1, T2, T3, T4, T5>, T3> {
typedef dmn_5<T0, T1, T2, T4, T5> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
struct Erase<dmn_6< T0, T1, T2, T3, T4, T5>, T4> {
typedef dmn_5<T0, T1, T2, T3, T5> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 >
struct Erase<dmn_6< T0, T1, T2, T3, T4, T5>, T5> {
typedef dmn_5<T0, T1, T2, T3, T4> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
struct Erase<dmn_7< T0, T1, T2, T3, T4, T5, T6>, T0> {
typedef dmn_6<T1, T2, T3, T4, T5, T6> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
struct Erase<dmn_7< T0, T1, T2, T3, T4, T5, T6>, T1> {
typedef dmn_6<T0, T2, T3, T4, T5, T6> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
struct Erase<dmn_7< T0, T1, T2, T3, T4, T5, T6>, T2> {
typedef dmn_6<T0, T1, T3, T4, T5, T6> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
struct Erase<dmn_7< T0, T1, T2, T3, T4, T5, T6>, T3> {
typedef dmn_6<T0, T1, T2, T4, T5, T6> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
struct Erase<dmn_7< T0, T1, T2, T3, T4, T5, T6>, T4> {
typedef dmn_6<T0, T1, T2, T3, T5, T6> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
struct Erase<dmn_7< T0, T1, T2, T3, T4, T5, T6>, T5> {
typedef dmn_6<T0, T1, T2, T3, T4, T6> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 >
struct Erase<dmn_7< T0, T1, T2, T3, T4, T5, T6>, T6> {
typedef dmn_6<T0, T1, T2, T3, T4, T5> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T0> {
typedef dmn_7<T1, T2, T3, T4, T5, T6, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T1> {
typedef dmn_7<T0, T2, T3, T4, T5, T6, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T2> {
typedef dmn_7<T0, T1, T3, T4, T5, T6, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T3> {
typedef dmn_7<T0, T1, T2, T4, T5, T6, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T4> {
typedef dmn_7<T0, T1, T2, T3, T5, T6, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T5> {
typedef dmn_7<T0, T1, T2, T3, T4, T6, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T6> {
typedef dmn_7<T0, T1, T2, T3, T4, T5, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 >
struct Erase<dmn_8< T0, T1, T2, T3, T4, T5, T6, T7>, T7> {
typedef dmn_7<T0, T1, T2, T3, T4, T5, T6> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T0> {
typedef dmn_8<T1, T2, T3, T4, T5, T6, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T1> {
typedef dmn_8<T0, T2, T3, T4, T5, T6, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T2> {
typedef dmn_8<T0, T1, T3, T4, T5, T6, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T3> {
typedef dmn_8<T0, T1, T2, T4, T5, T6, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T4> {
typedef dmn_8<T0, T1, T2, T3, T5, T6, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T5> {
typedef dmn_8<T0, T1, T2, T3, T4, T6, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T6> {
typedef dmn_8<T0, T1, T2, T3, T4, T5, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T7> {
typedef dmn_8<T0, T1, T2, T3, T4, T5, T6, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 >
struct Erase<dmn_9< T0, T1, T2, T3, T4, T5, T6, T7, T8>, T8> {
typedef dmn_8<T0, T1, T2, T3, T4, T5, T6, T7> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T0> {
typedef dmn_9<T1, T2, T3, T4, T5, T6, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T1> {
typedef dmn_9<T0, T2, T3, T4, T5, T6, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T2> {
typedef dmn_9<T0, T1, T3, T4, T5, T6, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T3> {
typedef dmn_9<T0, T1, T2, T4, T5, T6, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T4> {
typedef dmn_9<T0, T1, T2, T3, T5, T6, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T5> {
typedef dmn_9<T0, T1, T2, T3, T4, T6, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T6> {
typedef dmn_9<T0, T1, T2, T3, T4, T5, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T7> {
typedef dmn_9<T0, T1, T2, T3, T4, T5, T6, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T8> {
typedef dmn_9<T0, T1, T2, T3, T4, T5, T6, T7, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 >
struct Erase<dmn_10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>, T9> {
typedef dmn_9<T0, T1, T2, T3, T4, T5, T6, T7, T8> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T0> {
typedef dmn_10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T1> {
typedef dmn_10<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T2> {
typedef dmn_10<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T3> {
typedef dmn_10<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T4> {
typedef dmn_10<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T5> {
typedef dmn_10<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T6> {
typedef dmn_10<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T7> {
typedef dmn_10<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T8> {
typedef dmn_10<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T9> {
typedef dmn_10<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
struct Erase<dmn_11< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>, T10> {
typedef dmn_10<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T0> {
typedef dmn_11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T1> {
typedef dmn_11<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T2> {
typedef dmn_11<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T3> {
typedef dmn_11<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T4> {
typedef dmn_11<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T5> {
typedef dmn_11<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T6> {
typedef dmn_11<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T7> {
typedef dmn_11<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T8> {
typedef dmn_11<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T9> {
typedef dmn_11<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T10> {
typedef dmn_11<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 >
struct Erase<dmn_12< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>, T11> {
typedef dmn_11<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T0> {
typedef dmn_12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T1> {
typedef dmn_12<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T2> {
typedef dmn_12<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T3> {
typedef dmn_12<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T4> {
typedef dmn_12<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T5> {
typedef dmn_12<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T6> {
typedef dmn_12<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T7> {
typedef dmn_12<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T8> {
typedef dmn_12<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T9> {
typedef dmn_12<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T10> {
typedef dmn_12<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T11> {
typedef dmn_12<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 >
struct Erase<dmn_13< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>, T12> {
typedef dmn_12<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T0> {
typedef dmn_13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T1> {
typedef dmn_13<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T2> {
typedef dmn_13<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T3> {
typedef dmn_13<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T4> {
typedef dmn_13<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T5> {
typedef dmn_13<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T6> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T7> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T8> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T9> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T10> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T11> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T12> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 >
struct Erase<dmn_14< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>, T13> {
typedef dmn_13<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T0> {
typedef dmn_14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T1> {
typedef dmn_14<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T2> {
typedef dmn_14<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T3> {
typedef dmn_14<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T4> {
typedef dmn_14<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T5> {
typedef dmn_14<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T6> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T7> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T8> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T9> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T10> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T11> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T12> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T13> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 >
struct Erase<dmn_15< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>, T14> {
typedef dmn_14<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T0> {
typedef dmn_15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T1> {
typedef dmn_15<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T2> {
typedef dmn_15<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T3> {
typedef dmn_15<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T4> {
typedef dmn_15<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T5> {
typedef dmn_15<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T6> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T7> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T8> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T9> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T10> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T11> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T12> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T13> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T14> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 >
struct Erase<dmn_16< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>, T15> {
typedef dmn_15<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T0> {
typedef dmn_16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T1> {
typedef dmn_16<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T2> {
typedef dmn_16<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T3> {
typedef dmn_16<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T4> {
typedef dmn_16<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T5> {
typedef dmn_16<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T6> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T7> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T8> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T9> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T10> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T11> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T12> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T13> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T14> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T15> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 >
struct Erase<dmn_17< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>, T16> {
typedef dmn_16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T0> {
typedef dmn_17<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T1> {
typedef dmn_17<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T2> {
typedef dmn_17<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T3> {
typedef dmn_17<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T4> {
typedef dmn_17<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T5> {
typedef dmn_17<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T6> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T7> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T8> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T9> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T10> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T11> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T12> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T13, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T13> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T14, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T14> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T15, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T15> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T16, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T16> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T17> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 >
struct Erase<dmn_18< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>, T17> {
typedef dmn_17<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T0> {
typedef dmn_18<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T1> {
typedef dmn_18<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T2> {
typedef dmn_18<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T3> {
typedef dmn_18<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T4> {
typedef dmn_18<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T5> {
typedef dmn_18<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T6> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T7> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T8> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T9> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T10> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T11> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T12> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T13, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T13> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T14, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T14> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T15, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T15> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T16, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T16> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T17, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T17> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T18> Result;
}; 

template <class T0 , class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 , class T11 , class T12 , class T13 , class T14 , class T15 , class T16 , class T17 , class T18 >
struct Erase<dmn_19< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>, T18> {
typedef dmn_18<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> Result;
}; 




/****************************************
***           SWAP                    ***
*****************************************/



template <class T0, class T1,class T2> 
struct Swap<dmn_0<T0>, T1, T2> {       
  typedef dmn_0<T0> Result;            
};


template <class T1,class T2>           
struct Swap<dmn_0<T1>, T1, T2> {       
  typedef dmn_0<T2> Result;            
};


template <class T0, class T1,class T2> 
struct Swap<dmn_0<T0>, dmn_0<T1>, dmn_0<T2> > {       
  typedef dmn_0<T0> Result;            
};


template <class T1,class T2>           
struct Swap<dmn_0<T1>, dmn_0<T1>, dmn_0<T2> > {       
  typedef dmn_0<T2> Result;            
};


template <class D0,  class T1, class T2>
 struct Swap<dmn_1< D0>, T1, T2> {       
typedef dmn_1<typename Swap<D0,T1,T2>::Result   > Result;
}; 

template <class D0, class D1,  class T1, class T2>
 struct Swap<dmn_2< D0, D1>, T1, T2> {       
typedef dmn_2<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2,  class T1, class T2>
 struct Swap<dmn_3< D0, D1, D2>, T1, T2> {       
typedef dmn_3<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3,  class T1, class T2>
 struct Swap<dmn_4< D0, D1, D2, D3>, T1, T2> {       
typedef dmn_4<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4,  class T1, class T2>
 struct Swap<dmn_5< D0, D1, D2, D3, D4>, T1, T2> {       
typedef dmn_5<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5,  class T1, class T2>
 struct Swap<dmn_6< D0, D1, D2, D3, D4, D5>, T1, T2> {       
typedef dmn_6<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6,  class T1, class T2>
 struct Swap<dmn_7< D0, D1, D2, D3, D4, D5, D6>, T1, T2> {       
typedef dmn_7<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7,  class T1, class T2>
 struct Swap<dmn_8< D0, D1, D2, D3, D4, D5, D6, D7>, T1, T2> {       
typedef dmn_8<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8,  class T1, class T2>
 struct Swap<dmn_9< D0, D1, D2, D3, D4, D5, D6, D7, D8>, T1, T2> {       
typedef dmn_9<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9,  class T1, class T2>
 struct Swap<dmn_10< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9>, T1, T2> {       
typedef dmn_10<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10,  class T1, class T2>
 struct Swap<dmn_11< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10>, T1, T2> {       
typedef dmn_11<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11,  class T1, class T2>
 struct Swap<dmn_12< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11>, T1, T2> {       
typedef dmn_12<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11, class D12,  class T1, class T2>
 struct Swap<dmn_13< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12>, T1, T2> {       
typedef dmn_13<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result,
typename Swap<D12,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11, class D12, class D13,  class T1, class T2>
 struct Swap<dmn_14< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13>, T1, T2> {       
typedef dmn_14<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result,
typename Swap<D12,T1,T2>::Result,
typename Swap<D13,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11, class D12, class D13, class D14,  class T1, class T2>
 struct Swap<dmn_15< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14>, T1, T2> {       
typedef dmn_15<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result,
typename Swap<D12,T1,T2>::Result,
typename Swap<D13,T1,T2>::Result,
typename Swap<D14,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11, class D12, class D13, class D14, class D15,  class T1, class T2>
 struct Swap<dmn_16< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15>, T1, T2> {       
typedef dmn_16<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result,
typename Swap<D12,T1,T2>::Result,
typename Swap<D13,T1,T2>::Result,
typename Swap<D14,T1,T2>::Result,
typename Swap<D15,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11, class D12, class D13, class D14, class D15, class D16,  class T1, class T2>
 struct Swap<dmn_17< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16>, T1, T2> {       
typedef dmn_17<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result,
typename Swap<D12,T1,T2>::Result,
typename Swap<D13,T1,T2>::Result,
typename Swap<D14,T1,T2>::Result,
typename Swap<D15,T1,T2>::Result,
typename Swap<D16,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11, class D12, class D13, class D14, class D15, class D16, class D17,  class T1, class T2>
 struct Swap<dmn_18< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17>, T1, T2> {       
typedef dmn_18<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result,
typename Swap<D12,T1,T2>::Result,
typename Swap<D13,T1,T2>::Result,
typename Swap<D14,T1,T2>::Result,
typename Swap<D15,T1,T2>::Result,
typename Swap<D16,T1,T2>::Result,
typename Swap<D17,T1,T2>::Result   > Result;
}; 

template <class D0, class D1, class D2, class D3, class D4, class D5, class D6, class D7, class D8, class D9, class D10, class D11, class D12, class D13, class D14, class D15, class D16, class D17, class D18,  class T1, class T2>
 struct Swap<dmn_19< D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18>, T1, T2> {       
typedef dmn_19<typename Swap<D0,T1,T2>::Result,
typename Swap<D1,T1,T2>::Result,
typename Swap<D2,T1,T2>::Result,
typename Swap<D3,T1,T2>::Result,
typename Swap<D4,T1,T2>::Result,
typename Swap<D5,T1,T2>::Result,
typename Swap<D6,T1,T2>::Result,
typename Swap<D7,T1,T2>::Result,
typename Swap<D8,T1,T2>::Result,
typename Swap<D9,T1,T2>::Result,
typename Swap<D10,T1,T2>::Result,
typename Swap<D11,T1,T2>::Result,
typename Swap<D12,T1,T2>::Result,
typename Swap<D13,T1,T2>::Result,
typename Swap<D14,T1,T2>::Result,
typename Swap<D15,T1,T2>::Result,
typename Swap<D16,T1,T2>::Result,
typename Swap<D17,T1,T2>::Result,
typename Swap<D18,T1,T2>::Result   > Result;
}; 




/****************************************
***           PRINT dmn_i             ***
*****************************************/



template <class T0>                       
struct printTL<dmn_0<T0> > {              
	static void print() {                   
		std::cout <<  "\t" << __PRETTY_FUNCTION__ << "\n"; 
	}                                       
};                                    


template <class D0 >
struct printTL<dmn_1<D0 > > { 
static void print() {
printTL<D0>::print(); 
}
};


template <class D0 , class D1 >
struct printTL<dmn_2<D0 , D1 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
}
};


template <class D0 , class D1 , class D2 >
struct printTL<dmn_3<D0 , D1 , D2 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 >
struct printTL<dmn_4<D0 , D1 , D2 , D3 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 >
struct printTL<dmn_5<D0 , D1 , D2 , D3 , D4 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 >
struct printTL<dmn_6<D0 , D1 , D2 , D3 , D4 , D5 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 >
struct printTL<dmn_7<D0 , D1 , D2 , D3 , D4 , D5 , D6 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 >
struct printTL<dmn_8<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 >
struct printTL<dmn_9<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 >
struct printTL<dmn_10<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 >
struct printTL<dmn_11<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 >
struct printTL<dmn_12<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 >
struct printTL<dmn_13<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 >
struct printTL<dmn_14<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 >
struct printTL<dmn_15<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 >
struct printTL<dmn_16<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 >
struct printTL<dmn_17<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 , class D17 >
struct printTL<dmn_18<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 , D17 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
printTL<D17>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 , class D17 , class D18 >
struct printTL<dmn_19<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 , D17 , D18 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
printTL<D17>::print(); 
printTL<D18>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 , class D17 , class D18 , class D19 >
struct printTL<dmn_20<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 , D17 , D18 , D19 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
printTL<D17>::print(); 
printTL<D18>::print(); 
printTL<D19>::print(); 
}
};





/****************************************
***           PRINT union_i           ***
*****************************************/



template <class D0 >
struct printTL<union_1<D0 > > { 
static void print() {
printTL<D0>::print(); 
}
};


template <class D0 , class D1 >
struct printTL<union_2<D0 , D1 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
}
};


template <class D0 , class D1 , class D2 >
struct printTL<union_3<D0 , D1 , D2 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 >
struct printTL<union_4<D0 , D1 , D2 , D3 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 >
struct printTL<union_5<D0 , D1 , D2 , D3 , D4 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 >
struct printTL<union_6<D0 , D1 , D2 , D3 , D4 , D5 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 >
struct printTL<union_7<D0 , D1 , D2 , D3 , D4 , D5 , D6 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 >
struct printTL<union_8<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 >
struct printTL<union_9<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 >
struct printTL<union_10<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 >
struct printTL<union_11<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 >
struct printTL<union_12<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 >
struct printTL<union_13<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 >
struct printTL<union_14<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 >
struct printTL<union_15<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 >
struct printTL<union_16<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 >
struct printTL<union_17<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 , class D17 >
struct printTL<union_18<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 , D17 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
printTL<D17>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 , class D17 , class D18 >
struct printTL<union_19<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 , D17 , D18 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
printTL<D17>::print(); 
printTL<D18>::print(); 
}
};


template <class D0 , class D1 , class D2 , class D3 , class D4 , class D5 , class D6 , class D7 , class D8 , class D9 , class D10 , class D11 , class D12 , class D13 , class D14 , class D15 , class D16 , class D17 , class D18 , class D19 >
struct printTL<union_20<D0 , D1 , D2 , D3 , D4 , D5 , D6 , D7 , D8 , D9 , D10 , D11 , D12 , D13 , D14 , D15 , D16 , D17 , D18 , D19 > > { 
static void print() {
printTL<D0>::print(); 
printTL<D1>::print(); 
printTL<D2>::print(); 
printTL<D3>::print(); 
printTL<D4>::print(); 
printTL<D5>::print(); 
printTL<D6>::print(); 
printTL<D7>::print(); 
printTL<D8>::print(); 
printTL<D9>::print(); 
printTL<D10>::print(); 
printTL<D11>::print(); 
printTL<D12>::print(); 
printTL<D13>::print(); 
printTL<D14>::print(); 
printTL<D15>::print(); 
printTL<D16>::print(); 
printTL<D17>::print(); 
printTL<D18>::print(); 
printTL<D19>::print(); 
}
};



}


#endif
