// Copyright (C) 2009-2016 ETH Zurich
// Copyright (C) 2007?-2016 Center for Nanophase Materials Sciences, ORNL
// All rights reserved.
//
// See LICENSE.txt for terms of usage.
// See CITATION.txt for citation guidelines if you use this code for scientific publications.
//
// Author: Urs R. Haehner (haehneru@itp.phys.ethz.ch)
//
// This file defines the various cuts of the Brillouin zone.

#ifndef PHYS_LIBRARY_DOMAINS_QUANTUM_DOMAIN_BRILLOUIN_ZONE_CUT_BRILLOUIN_ZONE_CUT_TYPE_HPP
#define PHYS_LIBRARY_DOMAINS_QUANTUM_DOMAIN_BRILLOUIN_ZONE_CUT_BRILLOUIN_ZONE_CUT_TYPE_HPP

enum BrillouinZoneCutType {
  BRILLOUIN_ZONE_CUT_TEMPLATE,
  FERMI_SURFACE_SQUARE_2D_LATTICE,
  SQUARE_2D_LATTICE,
  BODY_CENTERED_TETRAGONAL_A,
  BODY_CENTERED_TETRAGONAL_B,
  SIMPLE_TETRAGONAL,
  TRICLINIC,
  FACE_CENTERED_CUBIC,
  BODY_CENTERED_CUBIC,
  SIMPLE_CUBIC,
  HEXAGONAL,
  RHOMBOHEDRAL_A,
  RHOMBOHEDRAL_B,
  SIMPLE_MONOCLINIC,
  ONE_FACE_CENTERED_MONOCLINIC_A,
  ONE_FACE_CENTERED_MONOCLINIC_B,
  SIMPLE_ORTHOROMBIC,
  BASE_CENTERED_ORTHORHOMBIC,
  BODY_CENTERED_ORTHOROMBIC,
  ALL_FACE_CENTERED_ORTHORHOMBIC_A,
  ALL_FACE_CENTERED_ORTHORHOMBIC_B
};

#endif  // PHYS_LIBRARY_DOMAINS_QUANTUM_DOMAIN_BRILLOUIN_ZONE_CUT_BRILLOUIN_ZONE_CUT_TYPE_HPP
