#ifndef PHYS_LIBRARY_PARAMETERS_PARAMETERS_SPECIALIZATION_SOLVER_PARAMETERS_COLLECTION_HPP
#define PHYS_LIBRARY_PARAMETERS_PARAMETERS_SPECIALIZATION_SOLVER_PARAMETERS_COLLECTION_HPP

//add more if needed
#ifndef USE_CTAUX
#error "Include the necessair solver parameters file"
#endif
#include "phys_library/parameters/parameters_specialization/solver_specializations/MC_solver_ct_aux_parameters.h"

#endif