//-*-C++-*-

/* 
 * 	 This is a C++ file generated by write_all.py 
 *
 * 	 author: Peter Staar  
 */ 


#include "domains/domain.h"                    
#include "domains/special_domains/dmn.h"                       

#include "domains/special_domains/dmn_0.h"
#include "domains/product_domains/dmn_1.h"
#include "domains/product_domains/dmn_2.h"
#include "domains/product_domains/dmn_3.h"
#include "domains/product_domains/dmn_4.h"
#include "domains/product_domains/dmn_5.h"
#include "domains/product_domains/dmn_6.h"
#include "domains/product_domains/dmn_7.h"
#include "domains/product_domains/dmn_8.h"
#include "domains/product_domains/dmn_9.h"
#include "domains/product_domains/dmn_10.h"
#include "domains/product_domains/dmn_11.h"
#include "domains/product_domains/dmn_12.h"
#include "domains/product_domains/dmn_13.h"
#include "domains/product_domains/dmn_14.h"
#include "domains/product_domains/dmn_15.h"
#include "domains/product_domains/dmn_16.h"
#include "domains/product_domains/dmn_17.h"
#include "domains/product_domains/dmn_18.h"
#include "domains/product_domains/dmn_19.h"
#include "domains/product_domains/dmn_20.h"


#include "domains/union_domains/union_1.h"
#include "domains/union_domains/union_2.h"
#include "domains/union_domains/union_3.h"
#include "domains/union_domains/union_4.h"
#include "domains/union_domains/union_5.h"
#include "domains/union_domains/union_6.h"
#include "domains/union_domains/union_7.h"
#include "domains/union_domains/union_8.h"
#include "domains/union_domains/union_9.h"
#include "domains/union_domains/union_10.h"
#include "domains/union_domains/union_11.h"
#include "domains/union_domains/union_12.h"
#include "domains/union_domains/union_13.h"
#include "domains/union_domains/union_14.h"
#include "domains/union_domains/union_15.h"
#include "domains/union_domains/union_16.h"
#include "domains/union_domains/union_17.h"
#include "domains/union_domains/union_18.h"
#include "domains/union_domains/union_19.h"
#include "domains/union_domains/union_20.h"

#include "domains/domain_type_operations.h"    

#include "function.h"                
