#! /usr/bin/env python3.1

import commands
import shutil
import os
import sys
import time

N = 20

cmd = "rm *~"
os.system(cmd)

cmd = "cd function_operations; python write_function_operations.py; rm *~"
os.system(cmd)

cmd = "cd domains; python write_domain_type_operations.py; python write_product_domains.py; python write_union_domains.py; ls -l  *~"
os.system(cmd)

def print_include_dmn_template(file, n):
    
    string_i = "#include \"dmn_INDEX.h\"\n"
    file.write(string_i.replace("INDEX", str(n)))

def print_include_union_template(file, n):
    
    string_i = "#include \"union_INDEX.h\"\n"
    file.write(string_i.replace("INDEX", str(n)))


file_name = "include_function_library.h"
file = open(file_name, 'w')

file.write("//-*-C++-*-\n\n")
file.write("/* \n * \t This is a C++ file generated by write_all.py \n *")

file.write("\n * \t author: Peter Staar  \n */ \n\n\n")

file.write("#include \"domain.h\"                    \n")
file.write("#include \"dmn.h\"                       \n\n")

for l in range(0,N+1):
    print_include_dmn_template(file, l)

file.write("\n\n")

for l in range(1,N+1):
    print_include_union_template(file, l)

file.write("\n#include \"domain_type_operations.h\"    \n")

file.write("\n#include \"function.h\"                \n")
	
file.close()
