//-*-C++-*-

/* 
 * 	 This is a C++ file generated by write_union_domains.py 
 *
 * 	 author: Peter Staar  
 */ 


#ifndef UNION_4_H_
#define UNION_4_H_

#include "domain.h"   
#include "type_list.h"   
#include "type_list_definitions.h"   

using namespace TL; 


template< typename domain_0_t,
		  typename domain_1_t,
		  typename domain_2_t,
		  typename domain_3_t>
class union_4 : public domain 
{

public:
 
 	typedef typename domain_0_t::this_type domain_typelist_0;
	typedef typename domain_1_t::this_type domain_typelist_1;
	typedef typename domain_2_t::this_type domain_typelist_2;
	typedef typename domain_3_t::this_type domain_typelist_3;
	
	typedef typename Append<domain_typelist_0, typename Append<domain_typelist_1, typename Append<domain_typelist_2, domain_typelist_3>::Result >::Result >::Result  this_type;
 
 	union_4();
 
 	void reset(); 
 
 	int operator()(int l);

protected:

	domain_0_t domain_0;
	domain_1_t domain_1;
	domain_2_t domain_2;
	domain_3_t domain_3;

};



template< typename domain_0_t,
		  typename domain_1_t,
		  typename domain_2_t,
		  typename domain_3_t>
union_4<domain_0_t, domain_1_t, domain_2_t, domain_3_t>::union_4():
	domain(),
	domain_0(),
	domain_1(),
	domain_2(),
	domain_3()
{

	size = domain_0.get_size() + domain_1.get_size() + domain_2.get_size() + domain_3.get_size();
	
	branch_domain_sizes.push_back(size);
	leaf_domain_sizes.push_back(size);
}

template< typename domain_0_t,
		  typename domain_1_t,
		  typename domain_2_t,
		  typename domain_3_t>
void union_4<domain_0_t, domain_1_t, domain_2_t, domain_3_t>::reset()
{
domain::reset();

domain_0.reset();
domain_1.reset();
domain_2.reset();
domain_3.reset();


	size = domain_0.get_size() + domain_1.get_size() + domain_2.get_size() + domain_3.get_size();
	
branch_domain_sizes.resize(0);
branch_domain_sizes.push_back(size);

leaf_domain_sizes.resize(0);
leaf_domain_sizes.push_back(size);
}

template< typename domain_0_t,
		  typename domain_1_t,
		  typename domain_2_t,
		  typename domain_3_t>
int union_4<domain_0_t, domain_1_t, domain_2_t, domain_3_t>::operator()(int l)
{
	 assert(l>=0 && l<size);
	 return l;
}

#endif
